//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BasiliskIIGUI.rc
//
#define IDC_FILETYPE_IMPORT             3
#define IDC_FILETYPE_EXPORT             4
#define IDC_FILETYPE_NEW                5
#define IDC_FILETYPE_DELETE             6
#define IDC_FILETYPE_SELECT_ALL         7
#define IDC_FILETYPE_EXPORT_SELECTED    8
#define IDC_FILETYPE_SELECT_ALL2        9
#define IDC_FILETYPE_DUPLICATE          10
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BASILISKIIGUI_DIALOG        102
#define IDD_NEW_HFV                     102
#define IDR_MAINFRAME                   128
#define IDD_PAGE_DISK                   129
#define IDD_PAGE_FLOPPY                 130
#define IDD_PAGE_CDROM                  131
#define IDD_PAGE_PORTS                  132
#define IDD_PAGE_MEMORY                 133
#define IDD_PAGE_SCREEN                 134
#define IDD_PAGE_SCSI                   135
#define IDD_PAGE_GENERAL                136
#define IDD_KEYBOARD                    137
#define IDD_PAGE_KEYBOARD               138
#define IDD_PAGE_TOOLS                  139
#define IDD_PAGE_ABOUT                  140
#define IDD_PAGE_ETHERNET               141
#define IDD_ASK_SCSI_REPLACEMENT        142
#define IDD_KEYBOARD_SAVE               143
#define IDD_PAGE_PRIORITIES             143
#define IDD_PAGE_AUDIO                  144
#define IDD_PAGE_DEBUG                  145
#define IDD_DASD_CONFIRM                147
#define IDD_RW_CONFIRM                  148
#define IDD_PAGE_MOUSE                  149
#define IDD_PAGE_EXPERIMENT             150
#define IDD_PAGE_DR                     151
#define IDD_PAGE_EXTFS                  152
#define IDD_DX_FULL_SCREEN_HELP         153
#define IDD_MOUNT_MODE_HELP             155
#define IDD_ROUTER_HELP                 156
#define IDD_ASK_NEW_PORT                157
#define IDD_FILETYPE_MAPPINGS           162
#define IDD_KEYBOARD_BACKUP             163
#define IDD_PAGE_SMP                    164
#define IDD_PAGE_ROUTER                 165
#define IDD_ASK_NEW_PORT_AND_IF         166
#define IDC_MAKEHFV_NAME                1002
#define IDC_SCSI_LIST_REPLACE_FROM      1002
#define IDC_PORTS_MODEM                 1003
#define IDC_MAKEHFV_SIZE                1003
#define IDC_PORTS_PRINTER               1004
#define IDC_SCSI_ENABLED                1004
#define IDC_SCREEN_FRAMESKIP            1005
#define IDC_SCREEN_FRAMESPERSECOND      1005
#define IDC_SCREEN_SLEEP_TICKS          1005
#define IDC_GENERAL_BOOT_DRIVER         1006
#define IDC_COMBO1                      1007
#define IDC_K_1                         1007
#define IDC_MEMORY_RAM_SIZE             1007
#define IDC_SCSI_LIST_REPLACE_TO        1007
#define IDC_ETHERNET_MAC                1007
#define IDC_CPU                         1007
#define IDC_TOOLS_GUI_AUTORESTART       1007
#define IDC_DISK_MOUNT_MODE             1007
#define IDC_NEW_INTERFACE_NUMBER        1007
#define IDC_KEYBOARD_TYPE               1007
#define IDC_K_2                         1008
#define IDC_ETHERNET_MODE               1008
#define IDC_K_3                         1009
#define IDC_SCREEN_WIDTH                1009
#define IDC_SCSI_LIST_DISABLED          1009
#define IDC_PRI_ETHERNET_IDLE           1009
#define IDC_ETHERNET_PERMANENT          1009
#define IDC_K_4                         1010
#define IDC_SCREEN_HEIGHT               1010
#define IDC_K_5                         1011
#define IDC_SCREEN_BITS                 1011
#define IDC_K_6                         1012
#define IDC_SCREEN_REFRESH_RATE         1012
#define IDC_K_7                         1013
#define IDC_K_8                         1014
#define IDC_K_9                         1015
#define IDC_K_0                         1016
#define IDC_FILETYPE_CREATOR            1016
#define IDC_K_PLUS                      1017
#define IDC_K_ACUTE                     1018
#define IDC_K_BACKSPACE                 1019
#define IDC_K_Q                         1020
#define IDC_K_W                         1021
#define IDC_K_E                         1022
#define IDC_K_R                         1023
#define IDC_K_T                         1024
#define IDC_K_Y                         1025
#define IDC_K_U                         1026
#define IDC_K_I                         1027
#define IDC_K_O                         1028
#define IDC_K_P                         1029
#define IDC_K_RUOTS_O                   1030
#define IDC_PRI_SERIAL_IN_RUN           1030
#define IDC_K_DOTDOT                    1031
#define IDC_PRI_SERIAL_IN_IDLE          1031
#define IDC_K_TAB                       1032
#define IDC_PRI_SERIAL_OUT_RUN          1032
#define IDC_K_A                         1033
#define IDC_PRI_SERIAL_OUT_IDLE         1033
#define IDC_K_S                         1034
#define IDC_PRI_CPU_RUN                 1034
#define IDC_K_D                         1035
#define IDC_PRI_CPU_IDLE                1035
#define IDC_K_F                         1036
#define IDC_PRI_60HZ_RUN                1036
#define IDC_K_G                         1037
#define IDC_PRI_60HZ_IDLE               1037
#define IDC_K_H                         1038
#define IDC_PRI_1HZ_RUN                 1038
#define IDC_K_J                         1039
#define IDC_PRI_1HZ_IDLE                1039
#define IDC_K_K                         1040
#define IDC_PRI_PRAM_RUN                1040
#define IDC_K_L                         1041
#define IDC_PRI_PRAM_IDLE               1041
#define IDC_K_OO                        1042
#define IDC_PRI_MOUSE_RUN               1042
#define IDC_K_AA                        1043
#define IDC_PRI_MOUSE_IDLE              1043
#define IDC_K_QUOTE                     1044
#define IDC_PRI_GDI_RUN                 1044
#define IDC_K_RET                       1045
#define IDC_PRI_GDI_IDLE                1045
#define IDC_K_CAPSLOCK                  1046
#define IDC_PRI_DX_RUN                  1046
#define IDC_K_LESSTHAN                  1047
#define IDC_PRI_DX_IDLE                 1047
#define IDC_K_Z                         1048
#define IDC_PRI_LFB_RUN                 1048
#define IDC_K_X                         1049
#define IDC_PRI_LFB_IDLE                1049
#define IDC_K_C                         1050
#define IDC_PRI_SOUND_STREAM_RUN        1050
#define IDC_K_V                         1051
#define IDC_PRI_SOUND_STREAM_IDLE       1051
#define IDC_K_B                         1052
#define IDC_K_N                         1053
#define IDC_K_M                         1054
#define IDC_K_COMMA                     1055
#define IDC_K_PERIOD                    1056
#define IDC_K_HYPHEN                    1057
#define IDC_K_RSHIFT                    1058
#define IDC_K_LSHIFT                    1059
#define IDC_K_LCONTROL                  1060
#define IDC_K_LWIN                      1061
#define IDC_K_LALT                      1062
#define IDC_K_ALTGR                     1063
#define IDC_K_RWIN                      1064
#define IDC_K_RCONTROL                  1065
#define IDC_K_SPACE                     1066
#define IDC_K_ESC                       1067
#define IDC_K_F1                        1068
#define IDC_K_F2                        1069
#define IDC_K_F3                        1070
#define IDC_K_F4                        1071
#define IDC_FILETYPE_LIST               1071
#define IDC_K_F5                        1072
#define IDC_FILETYPE_HFS2FAT            1072
#define IDC_K_F6                        1073
#define IDC_FILETYPE_FAT2HFS            1073
#define IDC_K_F7                        1074
#define IDC_FILETYPE_DOS                1074
#define IDC_K_F8                        1075
#define IDC_FILETYPE_TYPE               1075
#define IDC_K_F9                        1076
#define IDC_K_F10                       1077
#define IDC_FILETYPE_COMMENT            1077
#define IDC_K_F11                       1078
#define IDC_FILETYPE_STRIP              1078
#define IDC_K_F12                       1079
#define IDC_FILETYPE_HELP               1079
#define IDC_K_PRINTSCREEN               1080
#define IDC_FILETYPE_CONFLICT           1080
#define IDC_K_SCROLL_LOCK               1081
#define IDC_K_PAUSE                     1082
#define IDC_K_LIST                      1083
#define IDC_K_INSERT                    1084
#define IDC_K_HOME                      1085
#define IDC_K_PAGE_UP                   1086
#define IDC_K_DELETE                    1087
#define IDC_K_END                       1088
#define IDC_K_PAGE_DOWN                 1089
#define IDC_K_LEFT                      1090
#define IDC_K_DOWN                      1091
#define IDC_K_RIGHT                     1092
#define IDC_K_UP                        1093
#define IDC_K_NUMLOCK                   1094
#define IDC_K_NUMPAD_DIVIDE             1095
#define IDC_K_NUMPAD_MULTIPLE           1096
#define IDC_K_NUMPAD_MINUS              1097
#define IDC_K_NUMPAD_7                  1098
#define IDC_K_NUMPAD_8                  1099
#define IDC_K_NUMPAD_9                  1100
#define IDC_K_NUMPAD_PLUS               1101
#define IDC_K_NUMPAD_4                  1102
#define IDC_K_NUMPAD_5                  1103
#define IDC_K_NUMPAD_6                  1104
#define IDC_K_NUMPAD_1                  1106
#define IDC_K_NUMPAD_2                  1107
#define IDC_K_NUMPAD_3                  1108
#define IDC_K_NUMPAD_COMMA              1109
#define IDC_K_NUMPAD_0                  1110
#define IDC_K_NUMPAD_ENTER              1111
#define IDC_K_SECTION                   1112
#define IDC_KEYBOARD_EDIT_CODES         1113
#define IDC_KEYBOARD_RIGHT_MOUSE        1114
#define IDC_GENERAL_PREFS_PATH          1115
#define IDC_GENERAL_PREFS_LOAD          1116
#define IDC_GENERAL_PREFS_ASSOCIATE     1116
#define IDC_GENERAL_PREFS_SAVE          1117
#define IDC_GENERAL_PREFS_SAVE_AS       1118
#define IDC_GENERAL_PREFS_BROWSE        1118
#define IDC_GENERAL_BOOT_DRIVE          1119
#define IDC_GENERAL_MODEL_ID            1120
#define IDC_GENERAL_FPU_ENABLED         1121
#define IDC_GENERAL_OS8_OK              1122
#define IDC_MEMORY_ROM_PATH             1123
#define IDC_MEMORY_ROM_BROWSE           1124
#define IDC_MEMORY_OS8_OK               1125
#define IDC_TOOLS_IS_ON_TOP             1126
#define IDC_MEMORY_ROM_TYPE             1126
#define IDC_SCREEN_TYPE                 1127
#define IDC_MEMORY_ROM_CHECKSUM_CALC    1127
#define IDC_EXPERIMENT_LOWMEM_CACHE     1127
#define IDC_SCREEN_NTDX5HACK            1128
#define IDC_MEMORY_ROM_CHECKSUM         1128
#define IDC_TOOLS_DISABLE_SCREENSAVER   1128
#define IDC_KEYBOARD_MAP_FILE_PATH      1131
#define IDC_MEMORY_INFO                 1131
#define IDC_KEYBOARD_MAP_BROWSE         1132
#define IDC_MAKEHFV_BROWSE              1133
#define IDC_DISK_CREATE_HFV             1134
#define IDC_CD_ENABLED                  1135
#define IDC_DISK_ADD_VOLUME_FILE        1135
#define IDC_CD_LIST_INSTALLED           1136
#define IDC_CD_UP                       1139
#define IDC_CD_DOWN                     1140
#define IDC_CD_LIST_AVAILABLE           1141
#define IDC_CD_INSTALL                  1142
#define IDC_CD_REMOVE                   1143
#define IDC_FLOPPY_BOOT_ALLOWED         1144
#define IDC_FLOPPY_LIST_INSTALLED       1145
#define IDC_FLOPPY_LIST_AVAILABLE       1146
#define IDC_FLOPPY_INSTALL              1147
#define IDC_FLOPPY_REMOVE               1148
#define IDC_FLOPPY_UP                   1149
#define IDC_FLOPPY_DOWN                 1150
#define IDC_DISK_LIST_INSTALLED         1151
#define IDC_DISK_LIST_AVAILABLE         1152
#define IDC_DISK_INSTALL                1153
#define IDC_DISK_REMOVE                 1154
#define IDC_DISK_UP                     1155
#define IDC_DISK_DOWN                   1156
#define IDC_SCSI_ADD_DISABLED           1158
#define IDC_SCSI_DEL_DISABLED           1159
#define IDC_SCSIREPL_VENDOR             1159
#define IDC_SCSI_ADD_FROM               1160
#define IDC_SCSIREPL_PRODUCT            1160
#define IDC_SCSI_DEL_FROM               1161
#define IDC_SCSI_ADD_TO                 1162
#define IDC_SCSI_DEL_TO                 1163
#define IDC_K_FRIENDLY_NAME             1163
#define IDC_DISK_POLL_MEDIA             1164
#define IDC_PRI_ETHERNET_RUN            1165
#define IDC_PRI_DEFAULTS                1167
#define IDC_AUDIO_ENABLED               1168
#define IDC_DEBUG_SCSI_LOG_LEVEL        1169
#define IDC_AUDIO_SWITCHOUT             1169
#define IDC_DEBUG_SERIAL_LOG_LEVEL      1170
#define IDC_AUDIO_MYST                  1170
#define IDC_DEBUG_FILESYS_LOG_LEVEL     1171
#define IDC_AUDIO_STARTUP_SOUND         1171
#define IDC_SCREEN_SHOW_FPS             1172
#define IDC_KEYBOARD_STICKY_MENU        1173
#define IDC_SCREEN_DISABLE_98OPT        1173
#define IDC_ETHERNET_HARDWARE_ADDRESS   1174
#define IDC_ETHERNET_FAKE_ADDRESS       1175
#define IDC_CD_REAL_MODE_CD             1176
#define IDC_DASD_NAME                   1177
#define IDC_AUDIO_BUFFER_SIZE_8000      1178
#define IDC_AUDIO_BUFFER_COUNT          1179
#define IDC_AUDIO_BUFFER_SIZE_11025     1180
#define IDC_AUDIO_BUFFER_SIZE_22050     1181
#define IDC_AUDIO_BUFFER_SIZE_44100     1182
#define IDC_MOUSE_MOUSEWHEEL_STATIC2    1183
#define IDC_MOUSE_MOUSEWHEEL_STATIC1    1184
#define IDC_DISK_RW                     1185
#define IDC_PATH_TO_MOUNT               1186
#define IDC_MOUSE_RIGHT_MOUSE           1187
#define IDC_MOUSE_STICKY_MENU           1188
#define IDC_MOUSE_MOUSEWHEEL            1189
#define IDC_MOUSE_MOUSELINES            1190
#define IDC_MOUSE_MOUSEWHEEL_REVERSE_X  1191
#define IDC_MOUSE_MOUSEWHEEL_REVERSE_Y  1192
#define IDC_MOUSE_MOUSEWHEEL_CLICK_MODE 1193
#define IDC_MOUSE_MOUSEWHEEL_CUST_00    1194
#define IDC_MOUSE_MOUSEWHEEL_CUST_01    1195
#define IDC_MOUSE_MOUSEWHEEL_CUST_10    1196
#define IDC_MOUSE_MOUSEWHEEL_CUST_11    1197
#define IDC_MOUSE_MOUSEWHEEL_STATIC3    1198
#define IDC_MOUSE_MOUSEWHEEL_STATIC4    1199
#define IDC_MOUSE_MOUSEWHEEL_STATIC5    1200
#define IDC_MOUSE_MOUSEWHEEL_STATIC6    1201
#define IDC_KEYBOARD_USE_ALT_ESCAPE     1202
#define IDC_MOUSE_MOVEMENT              1202
#define IDC_KEYBOARD_USE_CONTROL_ESCAPE 1203
#define IDC_KEYBOARD_USE_ALT_TAB        1204
#define IDC_DEBUG_DISABLE_ACCURATE_TIMER 1205
#define IDC_KEYBOARD_USE_ALT_SPACE      1205
#define IDC_KEYBOARD_USE_ALT_ENTER      1206
#define IDC_FLOPPY_RW                   1207
#define IDC_EXTFS_TYPES                 1210
#define IDC_DR_DUMP                     1210
#define IDC_DR_DIS68K                   1211
#define IDC_EXTFS_ENABLED               1211
#define IDC_DR_COMPILEONLY              1212
#define IDC_EXTFS_A                     1212
#define IDC_DR_BREAK                    1213
#define IDC_EXTFS_B                     1213
#define IDC_DR_MAKETAGS                 1214
#define IDC_EXTFS_C                     1214
#define IDC_EXTFS_D                     1215
#define IDC_EXTFS_E                     1216
#define IDC_EXTFS_F                     1217
#define IDC_EXTFS_G                     1218
#define IDC_EXTFS_H                     1219
#define IDC_EXTFS_I                     1220
#define IDC_EXTFS_J                     1221
#define IDC_EXTFS_K                     1222
#define IDC_EXTFS_L                     1223
#define IDC_EXTFS_M                     1224
#define IDC_EXTFS_N                     1225
#define IDC_EXTFS_O                     1226
#define IDC_EXTFS_P                     1227
#define IDC_EXTFS_Q                     1228
#define IDC_EXTFS_R                     1229
#define IDC_EXTFS_S                     1230
#define IDC_EXTFS_T                     1231
#define IDC_EXTFS_U                     1232
#define IDC_EXTFS_V                     1233
#define IDC_EXTFS_W                     1234
#define IDC_EXTFS_X                     1235
#define IDC_EXTFS_Y                     1236
#define IDC_EXTFS_Z                     1237
#define IDC_EXTFS_NONE                  1238
#define IDC_EXTFS_ALL                   1239
#define IDC_EXTFS_PATH                  1240
#define IDC_EXTFS_BROWSE_PATH           1241
#define IDC_PORTS_FILE0                 1242
#define IDC_PORTS_FILE1                 1243
#define IDC_PORTS_FILE0_BROWSE          1244
#define IDC_PORTS_FILE1_BROWSE          1245
#define IDC_SCREEN_REFRESH_RATE_HELP    1245
#define IDC_MODE_LIST                   1246
#define IDC_MOUNT_MODE_HELP             1247
#define IDC_SMP_ETHERNET_1              1248
#define IDC_SMP_ETHERNET_2              1249
#define IDC_SMP_ETHERNET_3              1250
#define IDC_SMP_ETHERNET_4              1251
#define IDC_SMP_ETHERNET_5              1252
#define IDC_SMP_ETHERNET_6              1253
#define IDC_SMP_ETHERNET_7              1254
#define IDC_SMP_ETHERNET_8              1255
#define IDC_SMP_SERIALIN_1              1256
#define IDC_SMP_SERIALIN_2              1257
#define IDC_SMP_SERIALIN_3              1258
#define IDC_SMP_SERIALIN_4              1259
#define IDC_SMP_SERIALIN_5              1260
#define IDC_SMP_SERIALIN_6              1261
#define IDC_SMP_SERIALIN_7              1262
#define IDC_SMP_SERIALIN_8              1263
#define IDC_SMP_SERIALOUT_1             1264
#define IDC_SMP_SERIALOUT_2             1265
#define IDC_SMP_SERIALOUT_3             1266
#define IDC_SMP_SERIALOUT_4             1267
#define IDC_SMP_SERIALOUT_5             1268
#define IDC_SMP_SERIALOUT_6             1269
#define IDC_SMP_SERIALOUT_7             1270
#define IDC_SMP_SERIALOUT_8             1271
#define IDC_SMP_CPU_1                   1272
#define IDC_SMP_CPU_2                   1273
#define IDC_SMP_CPU_3                   1274
#define IDC_SMP_CPU_4                   1275
#define IDC_SMP_CPU_5                   1276
#define IDC_SMP_CPU_6                   1277
#define IDC_SMP_CPU_7                   1278
#define IDC_SMP_CPU_8                   1279
#define IDC_SMP_60HZ_1                  1280
#define IDC_SMP_60HZ_2                  1281
#define IDC_SMP_60HZ_3                  1282
#define IDC_SMP_60HZ_4                  1283
#define IDC_SMP_60HZ_5                  1284
#define IDC_SMP_60HZ_6                  1285
#define IDC_SMP_60HZ_7                  1286
#define IDC_SMP_60HZ_8                  1287
#define IDC_SMP_1HZ_1                   1288
#define IDC_SMP_1HZ_2                   1289
#define IDC_SMP_1HZ_3                   1290
#define IDC_SMP_1HZ_4                   1291
#define IDC_SMP_1HZ_5                   1292
#define IDC_SMP_1HZ_6                   1293
#define IDC_SMP_1HZ_7                   1294
#define IDC_SMP_1HZ_8                   1295
#define IDC_SMP_PRAM_1                  1296
#define IDC_SMP_PRAM_2                  1297
#define IDC_SMP_PRAM_3                  1298
#define IDC_SMP_PRAM_4                  1299
#define IDC_SMP_PRAM_5                  1300
#define IDC_SMP_PRAM_6                  1301
#define IDC_SMP_PRAM_7                  1302
#define IDC_SMP_PRAM_8                  1303
#define IDC_SMP_GUI_1                   1304
#define IDC_SMP_GUI_2                   1305
#define IDC_SMP_GUI_3                   1306
#define IDC_SMP_GUI_4                   1307
#define IDC_SMP_GUI_5                   1308
#define IDC_SMP_GUI_6                   1309
#define IDC_SMP_GUI_7                   1310
#define IDC_SMP_GUI_8                   1311
#define IDC_SMP_GDI_1                   1312
#define IDC_SMP_GDI_2                   1313
#define IDC_SMP_GDI_3                   1314
#define IDC_SMP_GDI_4                   1315
#define IDC_SMP_GDI_5                   1316
#define IDC_SMP_GDI_6                   1317
#define IDC_SMP_GDI_7                   1318
#define IDC_SMP_GDI_8                   1319
#define IDC_SMP_DX_1                    1320
#define IDC_SMP_DX_2                    1321
#define IDC_SMP_DX_3                    1322
#define IDC_SMP_DX_4                    1323
#define IDC_SMP_DX_5                    1324
#define IDC_SMP_DX_6                    1325
#define IDC_SMP_DX_7                    1326
#define IDC_SMP_DX_8                    1327
#define IDC_SMP_FB_1                    1328
#define IDC_SMP_FB_2                    1329
#define IDC_SMP_FB_3                    1330
#define IDC_SMP_FB_4                    1331
#define IDC_SMP_FB_5                    1332
#define IDC_SMP_FB_6                    1333
#define IDC_SMP_FB_7                    1334
#define IDC_SMP_FB_8                    1335
#define IDC_SMP_AUDIO_1                 1336
#define IDC_SMP_AUDIO_2                 1337
#define IDC_SMP_AUDIO_3                 1338
#define IDC_SMP_AUDIO_4                 1339
#define IDC_SMP_AUDIO_5                 1340
#define IDC_SMP_AUDIO_6                 1341
#define IDC_SMP_AUDIO_7                 1342
#define IDC_SMP_AUDIO_8                 1343
#define IDC_TOOLS_IDLE_SLEEP            1346
#define IDC_TOOLS_SLEEP_ENABLED         1347
#define IDC_ROUTER_ENABLE               1348
#define IDC_TOOLS_IDLE_MINUTES          1349
#define IDC_ROUTER_HELP                 1349
#define IDC_ROUTER_FTP_PORT_LIST        1350
#define IDC_ROUTER_NEW_FTP_PORT         1351
#define IDC_ROUTER_DEL_FTP_PORT         1352
#define IDC_ROUTER_LISTEN_PORT_LIST     1353
#define IDC_NEW_PORT_NUMBER             1353
#define IDC_ROUTER_NEW_LISTEN_PORT      1354
#define IDC_ROUTER_DEL_LISTEN_PORT      1355

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1354
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
